import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { AppWrapper } from '@/app/context/index';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Nesine Bülten',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        {<AppWrapper>{children}</AppWrapper>}
      </body>
    </html>
  );
}
